### ISSUE TITLE
Feature request: Add makefile

### ISSUE THREAD

**Issue by jtbx** [KCGD/openSourceSpidermanMeme#3]
Add makefile so we can use

    make

to compile the meme. GUIs are bloat anyways

**Comment by PQCraft** [comment]
You can use `xcf2png` and just add it as a dependency :trollface::+1:

**Comment by KCGD** [comment]
> You can use `xcf2png` and just add it as a dependency :trollface:👍

ooooh good idea

**Comment by githubcatw** [comment]
> You can use `xcf2png` and just add it as a dependency :trollface:👍

xcf2png doesn't support modern versions of GIMP, but ImageMagick's convert tool does
